/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nestor.calculadoragrafica;

/**
 *
 * @author nesto
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        IngresarDatos = new javax.swing.JButton();
        etiquetasigno = new javax.swing.JLabel();
        Dia = new javax.swing.JTextField();
        etiquetames = new javax.swing.JLabel();
        etiquetadia = new javax.swing.JLabel();
        SignoFinal = new javax.swing.JLabel();
        Mes = new javax.swing.JComboBox<>();
        jLayeredPane1 = new javax.swing.JLayeredPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Titulo.setFont(new java.awt.Font("Old English Text MT", 0, 24)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Signo Zodiacal");

        IngresarDatos.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        IngresarDatos.setText("Ingresar");
        IngresarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarDatosActionPerformed(evt);
            }
        });

        etiquetasigno.setFont(new java.awt.Font("Sitka Small", 3, 18)); // NOI18N
        etiquetasigno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetasigno.setText("Tu signo zodiacal es:");

        Dia.setFont(new java.awt.Font("Myanmar Text", 0, 18)); // NOI18N
        Dia.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        etiquetames.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        etiquetames.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetames.setText("Mes");

        etiquetadia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetadia.setText("Dia");

        SignoFinal.setFont(new java.awt.Font("OCR A Extended", 0, 24)); // NOI18N
        SignoFinal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SignoFinal.setText("signo aqui");

        Mes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre", " " }));

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 54, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(Titulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(etiquetames, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(etiquetadia, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(Mes, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(Dia, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(IngresarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(etiquetasigno, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(56, 66, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(SignoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(Titulo)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiquetames)
                    .addComponent(etiquetadia))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Mes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Dia, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(IngresarDatos)
                .addGap(26, 26, 26)
                .addComponent(etiquetasigno, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SignoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IngresarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarDatosActionPerformed
        // TODO add your handling code here:
        int dia = Integer.parseInt(Dia.getText());
        String mes = (String)Mes.getSelectedItem();
        
            if ((mes.equals("Enero") && dia >= 21) || (mes.equals("Febrero") && dia <= 19)) {
                SignoFinal.setText("Acuario");
            } else if ((mes.equals("Febrero") && dia >= 20) || (mes.equals("Marzo") && dia <= 20)) {
                SignoFinal.setText("Piscis");
            } else if ((mes.equals("Marzo") && dia >= 21) || (mes.equals("Abril") && dia <= 20)) {
                SignoFinal.setText("Aries");
            } else if ((mes.equals("Abril") && dia >= 21) || (mes.equals("Mayo") && dia <= 21)) {
                SignoFinal.setText("Taurus");
            } else if ((mes.equals("Mayo") && dia >= 22) || (mes.equals("Junio") && dia <= 21)) {
                SignoFinal.setText("Gemini");
            } else if ((mes.equals("Junio") && dia >= 22) || (mes.equals("Julio") && dia <= 22)) {
                SignoFinal.setText("Cancer");
            } else if ((mes.equals("Julio") && dia >= 23) || (mes.equals("Agosto") && dia <= 23)) {
                SignoFinal.setText("Leo");
            } else if ((mes.equals("Agosto") && dia >= 24) || (mes.equals("Septiembre") && dia <= 23)) {
                SignoFinal.setText("Virgo");
            } else if ((mes.equals("Septiembre") && dia >= 24) || (mes.equals("Octubre") && dia <= 23)) {
                SignoFinal.setText("Libra");
            } else if ((mes.equals("Octubre") && dia >= 24) || (mes.equals("Noviembre") && dia <= 22)) {
                SignoFinal.setText("Escorpio");
            } else if ((mes.equals("Noviembre") && dia >= 23) || (mes.equals("Diciembre") && dia <= 21)) {
                SignoFinal.setText("Sagitario");
            } else if ((mes.equals("Diciembre") && dia >= 22) || (mes.equals("Enero") && dia <= 20)) {
                SignoFinal.setText("Capricornio");
            } else if (dia > 31){
                SignoFinal.setText("Valores Invalidos");
            }
    }//GEN-LAST:event_IngresarDatosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Dia;
    private javax.swing.JButton IngresarDatos;
    private javax.swing.JComboBox<String> Mes;
    private javax.swing.JLabel SignoFinal;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel etiquetadia;
    private javax.swing.JLabel etiquetames;
    private javax.swing.JLabel etiquetasigno;
    private javax.swing.JLayeredPane jLayeredPane1;
    // End of variables declaration//GEN-END:variables
}
