/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.interfas;

/**
 *
 * @author Esteban y Nestor
 */
public class interfasframe extends javax.swing.JFrame {

    /**
     * Creates new form interfasframe
     */
    public interfasframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Respuesta = new javax.swing.JTextArea();
        Label1 = new javax.swing.JLabel();
        botoncerrar = new javax.swing.JButton();
        Dia = new javax.swing.JTextField();
        Mes = new javax.swing.JTextField();
        LabelDia = new javax.swing.JLabel();
        LabelMes = new javax.swing.JLabel();
        BotonAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora del zodiaco");

        Respuesta.setColumns(20);
        Respuesta.setRows(5);
        jScrollPane1.setViewportView(Respuesta);

        Label1.setText("Ingresa tu fecha");

        botoncerrar.setText("Cerrar");
        botoncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoncerrarActionPerformed(evt);
            }
        });

        Mes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MesActionPerformed(evt);
            }
        });

        LabelDia.setText("Dia:");

        LabelMes.setText("Mes:");

        BotonAceptar.setText("Aceptar");
        BotonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botoncerrar)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(LabelDia, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(Dia, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LabelMes, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Mes, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(95, 349, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BotonAceptar)
                            .addComponent(Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Label1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelDia)
                    .addComponent(LabelMes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonAceptar)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                .addComponent(botoncerrar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botoncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoncerrarActionPerformed

    }//GEN-LAST:event_botoncerrarActionPerformed

    private void MesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MesActionPerformed
    if(evt.getSource() == botoncerrar){
      System.exit(0);
    }
    }//GEN-LAST:event_MesActionPerformed

    private void BotonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAceptarActionPerformed
            int dia = Integer.parseInt(Dia.getText());
            int mes = Integer.parseInt(Mes.getText());
 
            if ((mes == 1 && dia >= 21) || (mes == 2 && dia <= 19)) {
              Respuesta.setText("Tu Signo Zodiacal es Acuario");

            } else if ((mes == 2 && dia >= 20) || (mes == 3 && dia <= 20)) {
              Respuesta.setText("Signo Zodiacal es Piscis");

            } else if ((mes == 3 && dia >= 21) || (mes == 4 && dia <= 20)) {
              Respuesta.setText("Tu Signo Zodiacal es Aries");

            } else if ((mes == 4 && dia >= 21) || (mes == 5 && dia <= 21)) {
              Respuesta.setText("Tu Signo Zodiacal es Taurus");

            } else if ((mes == 5 && dia >= 22) || (mes == 6 && dia <= 21)) {
              Respuesta.setText("Tu Signo Zodiacal es Gemini");

            } else if ((mes == 6 && dia >= 22) || (mes == 7 && dia <= 22)) {
              Respuesta.setText("Tu Signo Zodiacal es Cancer");
            
            } else if ((mes == 7 && dia >= 23) || (mes == 8 && dia <= 23)) {
              Respuesta.setText("Tu Signo Zodiacal es Leo");

            } else if ((mes == 8 && dia >= 24) || (mes == 9 && dia <= 23)) {
              Respuesta.setText("Tu Signo Zodiacal es Virgo");
            
            } else if ((mes == 9 && dia >= 24) || (mes == 10 && dia <= 23)) {
              Respuesta.setText("Tu Signo Zodiacal es Libra");

            } else if ((mes == 10 && dia >= 24) || (mes == 11 && dia <= 22)) {
              Respuesta.setText("Tu Signo Zodiacal es Escorpio");
             
            } else if ((mes == 11 && dia >= 23) || (mes == 12 && dia <= 21)) {
              Respuesta.setText("Tu Signo Zodiacal es Sagitario");
             
            } else if ((mes == 12 && dia >= 22) || (mes == 1 && dia <= 20)) {
              Respuesta.setText("Tu Signo Zodiacal es Capricornio");
    }//GEN-LAST:event_BotonAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfasframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfasframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfasframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfasframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfasframe().setVisible(true);
                new interfasframe().setBounds(0,0,11,11);
                new interfasframe().setLocationRelativeTo(null);
                new interfasframe().setResizable(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAceptar;
    private javax.swing.JTextField Dia;
    private javax.swing.JLabel Label1;
    private javax.swing.JLabel LabelDia;
    private javax.swing.JLabel LabelMes;
    private javax.swing.JTextField Mes;
    private javax.swing.JTextArea Respuesta;
    private javax.swing.JButton botoncerrar;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
